# Secret Manager — the only place secrets are stored. State and config files
# never hold real secret values; resources here either generate them inline
# (random_password) or expect them to be filled in via Console / gcloud.
#
# Each Cloud Run service mounts only the secrets it needs (see runtime
# service-account IAM in service_accounts.tf).

# ─── database-password ──────────────────────────────────────────────────────
# The Postgres app-user password. Generated by random_password in cloud_sql.tf;
# we mirror it into Secret Manager so Cloud Run can mount it as an env var.

resource "google_secret_manager_secret" "db_password" {
  project   = var.project_id
  secret_id = "database-password"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db_app_user.result
}

# ─── nextauth-secret ────────────────────────────────────────────────────────
# Auth.js needs a 32+ byte random value for signing session cookies. Generated
# here so the next-PR Cloud Run service can mount it directly.

resource "google_secret_manager_secret" "nextauth_secret" {
  project   = var.project_id
  secret_id = "nextauth-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "nextauth_secret" {
  secret      = google_secret_manager_secret.nextauth_secret.id
  secret_data = random_password.nextauth.result
}

resource "random_password" "nextauth" {
  length  = 48
  special = false # base64-friendly, no escaping concerns
}

# ─── google-oauth-client-secret ─────────────────────────────────────────────
# Empty placeholder. The actual value is created in Google Cloud Console
# (APIs & Services → Credentials → OAuth 2.0 Client). After creating the
# client, paste its secret into this Secret Manager secret:
#
#   echo -n "$YOUR_CLIENT_SECRET" | gcloud secrets versions add \
#     google-oauth-client-secret --data-file=-
#
# The resource here exists so the secret name + IAM are managed in Tofu.

resource "google_secret_manager_secret" "google_oauth_client_secret" {
  project   = var.project_id
  secret_id = "google-oauth-client-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

# Note: NO google_secret_manager_secret_version here. The first version gets
# created out-of-band when you paste in the real OAuth client secret. Tofu
# does not manage that version's content (it's a manually-rotated value).
