# Secret Manager — the only place secrets are stored. State and config files
# never hold real secret values; resources here either generate them inline
# (random_password) or expect them to be filled in via Console / gcloud.
#
# Each Cloud Run service mounts only the secrets it needs (see runtime
# service-account IAM in service_accounts.tf).

# ─── database-password ──────────────────────────────────────────────────────
# The Postgres app-user password. Generated by random_password in cloud_sql.tf;
# we mirror it into Secret Manager so Cloud Run can mount it as an env var.

resource "google_secret_manager_secret" "db_password" {
  project   = var.project_id
  secret_id = "database-password"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db_app_user.result
}

# ─── nextauth-secret ────────────────────────────────────────────────────────
# Auth.js needs a 32+ byte random value for signing session cookies. Generated
# here so the next-PR Cloud Run service can mount it directly.

resource "google_secret_manager_secret" "nextauth_secret" {
  project   = var.project_id
  secret_id = "nextauth-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "nextauth_secret" {
  secret      = google_secret_manager_secret.nextauth_secret.id
  secret_data = random_password.nextauth.result
}

resource "random_password" "nextauth" {
  length  = 48
  special = false # base64-friendly, no escaping concerns
}

# ─── google-oauth-client-secret ─────────────────────────────────────────────
# Empty placeholder. The actual value is created in Google Cloud Console
# (APIs & Services → Credentials → OAuth 2.0 Client). After creating the
# client, paste its secret into this Secret Manager secret:
#
#   echo -n "$YOUR_CLIENT_SECRET" | gcloud secrets versions add \
#     google-oauth-client-secret --data-file=-
#
# The resource here exists so the secret name + IAM are managed in Tofu.

resource "google_secret_manager_secret" "google_oauth_client_secret" {
  project   = var.project_id
  secret_id = "google-oauth-client-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

# Note: NO google_secret_manager_secret_version here. The first version gets
# created out-of-band when you paste in the real OAuth client secret. Tofu
# does not manage that version's content (it's a manually-rotated value).

# ─── football-data-api-key ───────────────────────────────────────────────────
# API key for football-data.org (free tier, 10 req/min). Sourced manually
# after sign-up at football-data.org/client/register. The quiniela-api
# Cloud Run service reads this on startup to seed teams + matches via
# FootballDataLoader (opt-in via APP_FOOTBALL_DATA_ENABLED=true).
#
# Populate after `tofu apply`:
#   echo -n "$YOUR_API_KEY" | gcloud secrets versions add \
#     football-data-api-key --data-file=-

resource "google_secret_manager_secret" "football_data_api_key" {
  project   = var.project_id
  secret_id = "football-data-api-key"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

# ─── sync-token (X-Sync-Token shared secret for /internal/**) ───────────────
# Generated by random_password so it rotates on `tofu apply` only when the
# resource is first created (or tainted). Cloud Scheduler embeds the result
# directly in the job's HTTP headers; the api Cloud Run service reads it via
# APP_SYNC_TOKEN (see cloud_run.tf).

resource "random_password" "sync_token" {
  length  = 48
  special = false
}

resource "google_secret_manager_secret" "sync_token" {
  project   = var.project_id
  secret_id = "sync-token"

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "sync_token" {
  secret      = google_secret_manager_secret.sync_token.id
  secret_data = random_password.sync_token.result
}

# ─── (retired) gemini-api-key ────────────────────────────────────────────────
# Octopus Paul moved from Google AI Studio (API-key auth, generativelanguage
# .googleapis.com) to Vertex AI (aiplatform.googleapis.com). Vertex authenticates
# via the runtime service account's ADC — no API key — and bills to the project's
# GCP credits, whereas AI Studio's free tier was depleted (HTTP 429) and is billed
# separately. So there is no longer a gemini-api-key secret: the API path is
# selected by APP_PAUL_PROVIDER=vertex (see cloud_run.tf) and authorized by
# roles/aiplatform.user on the api runtime SA (see service_accounts.tf).
